const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    //
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    //
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
    //
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    //
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',
    //
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    //
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    //
    GET_TOP_DOCTOR_SUCCESS: 'GET_TOP_DOCTOR_SUCCESS',
    GET_TOP_DOCTOR_FAILED: 'GET_TOP_DOCTOR_FAILED',
    //
    GET_ALL_DOCTOR_SUCCESS: 'GET_ALL_DOCTOR_SUCCESS',
    GET_ALL_DOCTOR_FAILED: 'GET_ALL_DOCTOR_FAILED',
    //
    SAVE_INFOR_DOCTOR_SUCCESS: 'SAVE_INFOR_DOCTOR_SUCCESS',
    SAVE_INFOR_DOCTOR_FAILED: 'SAVE_INFOR_DOCTOR_FAILED',
    //
    GET_DOCTOR_BY_ID_SUCCESS: 'GET_DOCTOR_BY_ID_SUCCESS',
    GET_DOCTOR_BY_ID_FAILED: 'GET_DOCTOR_BY_ID_FAILED',
    //
    GET_ALL_SCHEDULE_TIME_SUCCESS: 'GET_ALL_SCHEDULE_TIME_SUCCESS',
    GET_ALL_SCHEDULE_TIME_FAILED: 'GET_ALL_SCHEDULE_TIME_FAILED',
    //
    FETCH_ALL_DOCTOR_INFOR_START: 'FETCH_ALL_DOCTOR_INFOR_START',
    FETCH_ALL_DOCTOR_INFOR_SUCCESS: 'FETCH_ALL_DOCTOR_INFOR_SUCCESS',
    FETCH_ALL_DOCTOR_INFOR_FAILED: 'FETCH_ALL_DOCTOR_INFOR_FAILED'
})

export default actionTypes;